export const USERS_LIST_REQUEST = "USERS_LIST_REQUEST";
export const USERS_LIST_SUCCESS = "USERS_LIST_SUCCESS";
export const USERS_LIST_FAIL = "USERS_LIST_FAIL";

export const USERS_DELETE_REQUEST = "USERS_DELETE_REQUEST";
export const USERS_DELETE_SUCCESS = "USERS_DELETE_SUCCESS";
export const USERS_DELETE_FAIL = "USERS_DELETE_FAIL";

export const USERS_EDIT_REQUEST = "USERS_EDIT_REQUEST";
export const USERS_EDIT_SUCCESS = "USERS_EDIT_SUCCESS";
export const USERS_EDIT_FAIL = "USERS_EDIT_FAIL";

export const USERS_UPDATE_REQUEST = "USERS_UPDATE_REQUEST";
export const USERS_UPDATE_SUCCESS = "USERS_UPDATE_SUCCESS";
export const USERS_UPDATE_FAIL = "USERS_UPDATE_FAIL";

export const USERS_BLOCK_REQUEST = "USERS_BLOCK_REQUEST";
export const USERS_BLOCK_SUCCESS = "USERS_BLOCK_SUCCESS";
export const USERS_BLOCK_FAIL = "USERS_BLOCK_FAIL";

export const USERS_UNBLOCK_REQUEST = "USERS_UNBLOCK_REQUEST";
export const USERS_UNBLOCK_SUCCESS = "USERS_UNBLOCK_SUCCESS";
export const USERS_UNBLOCK_FAIL = "USERS_UNBLOCK_FAIL";

export const LIST_DOCTORS_REQUEST = "LIST_DOCTORS_REQUEST";
export const LIST_DOCTORS_SUCCESS = "LIST_DOCTORS_SUCCESS";
export const LIST_DOCTORS_FAIL = "LIST_DOCTORS_FAIL";
