export const USER_LOGIN = "USER_LOGIN";
export const GET_USER_INFO = "GET_USER_INFO";
export  const USER_LOGOUT = "USER_LOGOUT";



export const VIEWALL_DOCTORS_REQUEST = "VIEWALL_DOCTORS_REQUEST";
export const VIEWALL_DOCTORS_SUCCESS = "VIEWALL_DOCTORS_SUCCESS";
export const VIEWALL_DOCTORS_FAIL = "VIEWALL_DOCTORS_FAIL";

